const PDFDocument = require("pdfkit");

const COLORS = {
  copper: "#c9752f",
  teal: "#1ea896",
  amethyst: "#8b5cf6",
  ink: "#1c1c22",
  muted: "#6b7280",
};

const buildReportPdf = (summary) =>
  new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: "A4" });
    const chunks = [];

    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    doc
      .fillColor(COLORS.copper)
      .fontSize(24)
      .font("Helvetica-Bold")
      .text("Sales Report", { align: "left" });
    doc
      .fillColor(COLORS.muted)
      .fontSize(10)
      .font("Helvetica")
      .text(`Generated ${new Date(summary.generatedAt).toLocaleString()}`);
    doc.moveDown(1.2);
    const { totals } = summary;
    const boxWidth = 150;
    const boxY = doc.y;
    const boxLabels = [
      ["Total Orders", totals.totalOrders],
      ["Total Revenue", `$${totals.totalRevenue}`],
      ["Avg Order Value", `$${totals.avgOrderValue}`],
    ];

    boxLabels.forEach(([label, value], i) => {
      const x = 50 + i * (boxWidth + 15);
      doc
        .roundedRect(x, boxY, boxWidth, 60, 8)
        .fillAndStroke("#f4f1ea", "#e5ded0");
      doc
        .fillColor(COLORS.muted)
        .fontSize(9)
        .text(label.toUpperCase(), x + 14, boxY + 12);
      doc
        .fillColor(COLORS.ink)
        .fontSize(18)
        .font("Helvetica-Bold")
        .text(String(value), x + 14, boxY + 28);
      doc.font("Helvetica");
    });

    doc.y = boxY + 80;
    doc.moveDown(1);

    const drawTable = (title, rows, columns) => {
      doc
        .fillColor(COLORS.teal)
        .fontSize(14)
        .font("Helvetica-Bold")
        .text(title);
      doc.moveDown(0.4);
      doc.fillColor(COLORS.ink).fontSize(10).font("Helvetica-Bold");

      const startX = 50;
      let y = doc.y;
      const colWidth = 495 / columns.length;

      columns.forEach((col, i) => {
        doc.text(col.label, startX + i * colWidth, y, { width: colWidth });
      });
      y += 16;
      doc
        .moveTo(startX, y)
        .lineTo(startX + 495, y)
        .strokeColor("#d8d2c4")
        .stroke();
      y += 6;

      doc.font("Helvetica").fontSize(10);
      rows.forEach((row) => {
        columns.forEach((col, i) => {
          doc.text(String(row[col.key]), startX + i * colWidth, y, {
            width: colWidth,
          });
        });
        y += 18;
      });

      doc.y = y + 14;
    };

    drawTable("Revenue by Category", summary.byCategory, [
      { label: "Category", key: "category" },
      { label: "Orders", key: "orders" },
      { label: "Revenue ($)", key: "revenue" },
    ]);

    drawTable("Revenue by Region", summary.byRegion, [
      { label: "Region", key: "region" },
      { label: "Orders", key: "orders" },
      { label: "Revenue ($)", key: "revenue" },
    ]);

    drawTable("Top 5 Products", summary.topProducts, [
      { label: "Product", key: "product" },
      { label: "Orders", key: "orders" },
      { label: "Revenue ($)", key: "revenue" },
    ]);

    doc.moveDown(1);
    doc
      .fillColor(COLORS.muted)
      .fontSize(9)
      .text(
        "Generated by FlyRank BE PDF Report Generator",
        50,
        doc.page.height - 60,
        {
          align: "center",
          width: 495,
        },
      );

    doc.end();
  });

module.exports = { buildReportPdf };
